spring:
  profiles:
    active: prod

server:
  shutdown: graceful
  compression:
    enabled: true

springdoc:
  swagger-ui:
    path: /api-docs

findex:
  openapi:
    base-url: https://apis.data.go.kr/1160100/service
    service-key: 0af09ae64845fbe85b981f8ddcf00a5a83c90fc014f006f87a51343cb874af75
