spring:
  profiles:
    active: prod

server:
  shutdown: graceful
  compression:
    enabled: true

springdoc:
  swagger-ui:
    path: /api-docs

findex:
  openapi:
    base-url: https://apis.data.go.kr/1160100/service
    service-key: 66d5f5e24b0699ab4f1cec248a412beb68bf13b064c5ed68445d9a39acdcdb05
