server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: ymSzmrMDpYYDqajCXaXgNEzdwLXJaZAs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
